#!/bin/bash

set -e

target="$1"
venv="${target}/opt/datascrubber"

mkdir -p "$venv" "${target}/usr/bin"
virtualenv --python=python3 "$venv"
. "${venv}/bin/activate"

pip install --upgrade pip 
pip install -r requirements.txt
pip install .

cp "bin/datascrubber" "${target}/usr/bin/datascrubber"
chmod 0755 "${target}/usr/bin/datascrubber"
sed -i -e '1d' -e '2i #!/opt/datascrubber/bin/python3' "${target}/usr/bin/datascrubber"
